[platformio]
src_dir = .
default_envs = ground, bus_01, bus_02, bus_03

[env]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
  sandeepmistry/LoRa@0.8.0
  mikalhart/TinyGPSPlus@1.0.3
  bblanchon/ArduinoJson@7.4.2
build_flags =
  -D SONGTHAEW_CI_BUILD

[env:ground]
build_src_filter = +<Songthaew_V03_ground.ino>

[env:bus_01]
build_src_filter = +<Songthaew_V03_vehicle.ino>
build_flags =
  ${env.build_flags}
  -D VEHICLE_ID=\"BUS_01\"

[env:bus_02]
build_src_filter = +<Songthaew_V03_vehicle.ino>
build_flags =
  ${env.build_flags}
  -D VEHICLE_ID=\"BUS_02\"

[env:bus_03]
build_src_filter = +<Songthaew_V03_vehicle.ino>
build_flags =
  ${env.build_flags}
  -D VEHICLE_ID=\"BUS_03\"
